
using UnityEngine;
using UnityEngine.SceneManagement;


public class PuntoMeta : MonoBehaviour
{
        private void OnTriggerEnter2D(Collider2D other)
    {
        if (other.CompareTag("Player"))
        {
        
            if (ContadorElementos.instancia != null && 
                ContadorElementos.instancia.elementosBuenos >= ContadorElementos.instancia.totalElementosBuenos)
            {
                Debug.Log("Â¡LlegÃ³ a la meta con todos los elementos! Victoria ðŸš€");
                SceneManager.LoadScene("Victoria"); 
            }
            else
            {
                Debug.Log("No recolectÃ³ todo, no puede ganar aÃºn");
            }
        }
    }
}